### ISSUE TITLE
Method IProblem.getModel() is missing

### ISSUE THREAD

**Issue by arnaud-m** [chocoteam/pf4cs#1]
I understand that the class Model is in choco-solver, but it is an issue. 
One could define a generic IProblem interface.

Beside, the indentation is weird in the github viewer.

**Comment by cprudhom** [comment]
Anyone can define it own implementation of such a method but since pf4cs should not depend on a specific solver, there is no good reason to create it.
We could use generics, but I'm not enclin to that.

**Comment by cprudhom** [comment]
see #2
